version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: victorious-postgres
    environment:
      POSTGRES_DB: victorious
      POSTGRES_USER: db
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgressql/postgres_data

volumes:
  postgres_data:
